# src/config.py
import os
from dotenv import load_dotenv

load_dotenv()

WHATSAPP_BOT_TOKEN = os.getenv('WHATSAPP_BOT_TOKEN')
CLICKUP_API_TOKEN = os.getenv('CLICKUP_API_TOKEN')
CLICKUP_SPACE_ID = os.getenv('CLICKUP_SPACE_ID')
CLICKUP_FOLDER_ID = os.getenv('CLICKUP_FOLDER_ID')
CLICKUP_CRM_LIST_NAME = os.getenv('CLICKUP_CRM_LIST_NAME', 'CRM Clientes')
GOOGLE_CALENDAR_ID = os.getenv('GOOGLE_CALENDAR_ID')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
EMAIL_SENDER = os.getenv('EMAIL_SENDER')
EMAIL_PASSWORD = os.getenv('EMAIL_PASSWORD')
